# Generated by Django 5.1.1 on 2024-10-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_alter_categoria_options_alter_subcategoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'verbose_name_plural': 'Sub Categorías'},
        ),
        migrations.RenameField(
            model_name='subcategoria',
            old_name='categoria',
            new_name='Categoria',
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la categoría', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la subcategoría', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('Categoria', 'descripcion')},
        ),
    ]
